### ISSUE TITLE
Benchmars

### ISSUE THREAD

**Issue by cht8687** [jonschlinkert/pad-left#9]
In Benchmarks section, I see you point to the same repo. 
should we update it?

**Comment by jonschlinkert** [comment]
to what?

**Comment by cht8687** [comment]
Benchmarks for node.js v6.1.0 versus left-pad.

Benchmarks for node.js v6.1.0 versus stevemao/left-pad.

The two links are same.... 'left-pad' and 'stevemao/left-pad'

**Comment by jonschlinkert** [comment]
would have probably taken 50% of the amount of time to just do a pr to fix the link instead of creating issues on two different projects to explain that a link is broken.

**Comment by cht8687** [comment]
@jonschlinkert  You misunderstood me. I feel it is better to raise an issue first for project like this. ( which has large downloads).  After the discussion, I am happy to make any PR. 

I was just viewing all the issues in left-pad and saw your issue ticket.

I am happy to submit a PR once you think it's necessary.

I saw nothing I did was wrong. : )

Question for you:

Since stevemao/left-pad is currently the repo for left-pad module, how do I modified this section?
should we keep the second section?

**Comment by jonschlinkert** [comment]
> Since stevemao/left-pad is currently the repo for left-pad module

left-pad was updated to use code that is very similar to the code that was already used in the underlying library used in this module (repeat-string). Sindre Sorhus did the same thing with `repeating`.  I think this is terrible open source, code theft shouldn't be encouraged. The only reason I added benchmarks is to show that despite using code from a this library, left-pad and repeating still aren't as performant. This is what happens when you copy code you don't understand.

edit: and sorry, a pr would be great. but fwiw I try not to think about left-pad. Regardless of the reasoning behind using that library, it should have been deprecated
